# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 16:08
from __future__ import unicode_literals

from django.db import migrations


def forwards(apps, schema_editor):
    """
    Set IBAN as NULL instead of empty string to enforce uniqueness at db level
    """
    User = apps.get_model('accounts', 'User')
    for user in User.objects.all():
        if not user.iban:
            user.iban = None
            user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards, lambda *args: None)
    ]
