# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 16:11
from __future__ import unicode_literals

from django.db import migrations
import localflavor.generic.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20161123_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='iban',
            field=localflavor.generic.models.IBANField('IBAN', None, null=True, unique=True),
        ),
    ]
